---

- include: install.yml

- name: Detect Docker API version
  shell: "docker version | grep API | grep -oE '[0-9.]+' | head -n 1"
  register: docker_api_version

- name: Start the Rancher Docker container
  docker: |
    image="rancher/server"
    ports="8080:{{ rancher_port }}"
    docker_api_version="{{ docker_api_version.stdout }}"

- name: Wait for the daemon to start up
  wait_for: port=8080
